apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: editor-sa-rolebinding
  namespace: {{.Values.namespace}}
subjects:
- kind: ServiceAccount
  name: test-minikube-sa
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io


