apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: editors-{{ .Values.username }}
  namespace: {{.Values.namespace}}
subjects:
- kind: User
  name: {{ .Values.username }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
