---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pmx.bottomline.com
  resources:
  - customclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pmx.bottomline.com
  resources:
  - customclusters/finalizers
  verbs:
  - update
- apiGroups:
  - pmx.bottomline.com
  resources:
  - customclusters/status
  verbs:
  - get
  - patch
  - update
